[package]
name = "sigma-serve"
version = "0.1.0"
edition = "2024"
authors = ["František Hrubý <frantisek@hruby.xyz>"]
description = "sigma-serve-rs is a simple, lightweight HTTP server written in Rust."
license = "MIT"

[dependencies]
